import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-white">
      <Navbar />
      
      <main className="mx-auto max-w-4xl px-6 pt-32 pb-24 md:px-8">
        <div className="border-b border-gray-100 pb-8">
          <span className="text-xs font-bold uppercase tracking-widest text-[#79716B]">
            Legal Document
          </span>
          <h1 className="mt-2 text-3xl font-extrabold tracking-tight text-[#121212] sm:text-4xl md:text-5xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-sm text-[#79716B]">
            Last updated: July 8, 2026
          </p>
        </div>

        <div className="prose prose-neutral mt-10 max-w-none text-[15px] leading-relaxed text-gray-700 space-y-8">
          <p>
            Welcome to SubCaps. Please read these Terms of Service (&quot;Terms&quot;) carefully before using the SubCaps website and captioning/subtitling software services (the &quot;Service&quot;) operated by SubCaps Inc. (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;).
          </p>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-[#121212] md:text-2xl">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using our Service, you agree to be bound by these Terms and our Privacy Policy. If you disagree with any part of the terms, you may not access the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-[#121212] md:text-2xl">
              2. Description of Service
            </h2>
            <p>
              SubCaps provides an automated, AI-powered video captioning and subtitling tool that allows users to upload video files, auto-detect spoken language, transcribe content, and apply dynamic subtitle styles/templates to export styled videos.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-[#121212] md:text-2xl">
              3. User Accounts &amp; Security
            </h2>
            <p>
              When you create an account with us, you must provide accurate and complete information. You are solely responsible for maintaining the confidentiality of your account credentials and password. You agree to accept responsibility for all activities that occur under your account.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-[#121212] md:text-2xl">
              4. Subscription Billing &amp; Cancellations
            </h2>
            <p>
              Some parts of the Service are billed on a subscription basis (&quot;Subscriptions&quot;). You will be billed in advance on a recurring and periodic cycle (monthly or annually). 
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>
                <strong>Free Plan:</strong> Includes 5 videos per month with a SubCaps watermark. No credit card required.
              </li>
              <li>
                <strong>Pro Plan:</strong> Billed monthly or annually. Includes unlimited videos and custom styles with no watermark.
              </li>
              <li>
                <strong>Cancellations:</strong> You can cancel your subscription at any time through your account dashboard. Your account will remain active until the end of your current billing period.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-[#121212] md:text-2xl">
              5. User Content &amp; Media Ownership
            </h2>
            <p>
              You retain all ownership rights, copyrights, and intellectual property rights to the videos you upload and the transcripts/subtitles generated by the Service. We do not claim any ownership over your content. By uploading content, you grant us a temporary, worldwide license solely to process and encode your video files to deliver the subtitle service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-[#121212] md:text-2xl">
              6. Limitation of Liability
            </h2>
            <p>
              In no event shall SubCaps, nor its directors, employees, or partners, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-[#121212] md:text-2xl">
              7. Changes to Terms
            </h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide at least 30 days notice prior to any new terms taking effect. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
            </p>
          </section>

          <section className="space-y-3 border-t border-gray-100 pt-6">
            <h2 className="text-lg font-bold text-[#121212]">
              Contact Us
            </h2>
            <p className="text-sm">
              If you have any questions about these Terms, please contact us at{" "}
              <a href="mailto:support@subcaps.com" className="font-semibold text-[#121212] underline hover:text-[#79716B]">
                legal@subcaps.com
              </a>.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
